import "./globals.css";
import Footer from "@/components/Footer/Footer";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iransans = localFont({
  src: [
    {
      path: "./../../public/assets/fonts/IRANSans/fonts/woff2/IRANSansWeb(FaNum).woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./../../public/assets/fonts/IRANSans/fonts/woff2/IRANSansWeb(FaNum)_Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" sizes="32x32" />
      </head>
      <body className={`min-h-screen ${iransans.className}`}>
        <Toaster />
        <Navbar />
        <div className="container mx-auto">
          <Providers>{children}</Providers>
        </div>
        <Footer />
      </body>
    </html>
  );
}
